### ISSUE TITLE
Facebook API Update

### ISSUE THREAD

**Issue by missedtheboat** [tmort/Socialite#101]
It looks like this needs to updated for continued support after the deprecation of the Facebook Graph API v1.0.

https://developers.facebook.com/docs/apps/upgrading

**Comment by tmort** [comment]
@missedtheboat Thanks for the heads up! If you'd like you can update the socialite facebook integration and I'll pull it into the main branch.

**Comment by missedtheboat** [comment]
@tmort no problem, I'll try to get a pr ready over the weekend.
